apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName | quote }}
{{ include "mychart.labels" . | indent 2 }}   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.imageName}}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ required "Containerport is not defined" .Values.service.containerPort }}

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
